# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 180)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 321, 181))
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.normal = QtWidgets.QWidget()
        self.normal.setObjectName("normal")
        self.labelImage = QtWidgets.QLabel(self.normal)
        self.labelImage.setGeometry(QtCore.QRect(60, 0, 170, 170))
        self.labelImage.setText("")
        self.labelImage.setObjectName("labelImage")
        self.btnLeft = QtWidgets.QPushButton(self.normal)
        self.btnLeft.setGeometry(QtCore.QRect(0, 60, 51, 32))
        self.btnLeft.setObjectName("btnLeft")
        self.btnOK = QtWidgets.QPushButton(self.normal)
        self.btnOK.setGeometry(QtCore.QRect(0, 150, 51, 32))
        self.btnOK.setObjectName("btnOK")
        self.btnRight = QtWidgets.QPushButton(self.normal)
        self.btnRight.setGeometry(QtCore.QRect(240, 60, 51, 32))
        self.btnRight.setObjectName("btnRight")
        self.tabWidget.addTab(self.normal, "")
        self.menu = QtWidgets.QWidget()
        self.menu.setObjectName("menu")
        self.btnSpeedInc = QtWidgets.QPushButton(self.menu)
        self.btnSpeedInc.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.btnSpeedInc.setObjectName("btnSpeedInc")
        self.btnBrightInc = QtWidgets.QPushButton(self.menu)
        self.btnBrightInc.setGeometry(QtCore.QRect(10, 70, 41, 41))
        self.btnBrightInc.setObjectName("btnBrightInc")
        self.btnBrightDec = QtWidgets.QPushButton(self.menu)
        self.btnBrightDec.setGeometry(QtCore.QRect(240, 70, 41, 41))
        self.btnBrightDec.setObjectName("btnBrightDec")
        self.btnSpeedDec = QtWidgets.QPushButton(self.menu)
        self.btnSpeedDec.setGeometry(QtCore.QRect(240, 10, 41, 41))
        self.btnSpeedDec.setObjectName("btnSpeedDec")
        self.lcdSpeed = QtWidgets.QLCDNumber(self.menu)
        self.lcdSpeed.setGeometry(QtCore.QRect(120, 20, 64, 31))
        self.lcdSpeed.setObjectName("lcdSpeed")
        self.lcdBright = QtWidgets.QLCDNumber(self.menu)
        self.lcdBright.setGeometry(QtCore.QRect(120, 70, 64, 31))
        self.lcdBright.setObjectName("lcdBright")
        self.btnShutdown = QtWidgets.QPushButton(self.menu)
        self.btnShutdown.setGeometry(QtCore.QRect(150, 140, 91, 32))
        self.btnShutdown.setObjectName("btnShutdown")
        self.btnEnde = QtWidgets.QPushButton(self.menu)
        self.btnEnde.setGeometry(QtCore.QRect(60, 140, 91, 32))
        self.btnEnde.setObjectName("btnEnde")
        self.btnBrightIncFast = QtWidgets.QPushButton(self.menu)
        self.btnBrightIncFast.setGeometry(QtCore.QRect(60, 70, 41, 41))
        self.btnBrightIncFast.setObjectName("btnBrightIncFast")
        self.btnBrightDecFast = QtWidgets.QPushButton(self.menu)
        self.btnBrightDecFast.setGeometry(QtCore.QRect(190, 70, 41, 41))
        self.btnBrightDecFast.setObjectName("btnBrightDecFast")
        self.tabWidget.addTab(self.menu, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnLeft.setText(_translate("MainWindow", "<-"))
        self.btnOK.setText(_translate("MainWindow", "OK"))
        self.btnRight.setText(_translate("MainWindow", "->"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.normal), _translate("MainWindow", "Use"))
        self.btnSpeedInc.setText(_translate("MainWindow", "+"))
        self.btnBrightInc.setText(_translate("MainWindow", "+"))
        self.btnBrightDec.setText(_translate("MainWindow", "-"))
        self.btnSpeedDec.setText(_translate("MainWindow", "-"))
        self.btnShutdown.setText(_translate("MainWindow", "Shutdown"))
        self.btnEnde.setText(_translate("MainWindow", "Ende"))
        self.btnBrightIncFast.setText(_translate("MainWindow", "+ +"))
        self.btnBrightDecFast.setText(_translate("MainWindow", "- -"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.menu), _translate("MainWindow", "Menu"))

